export const FEATURE_CODES = {
  BASIC_ANALYSIS: 'BASIC_ANALYSIS',
  EXPANDED_JOB_MATCHING: 'EXPANDED_JOB_MATCHING',
  JOB_SPECIFIC_ANALYSIS: 'JOB_SPECIFIC_ANALYSIS',
  AI_CV_RECOMMENDATIONS: 'AI_CV_RECOMMENDATIONS',
  AI_DETAILED_REPORT: 'AI_DETAILED_REPORT',
  PDF_EXPORT: 'PDF_EXPORT',
  FULL_KNOWLEDGE_BASE: 'FULL_KNOWLEDGE_BASE',
  ANALYSIS_HISTORY: 'ANALYSIS_HISTORY',
  SUPPORT_CHAT: 'SUPPORT_CHAT',
  JOB_MATCH_LIMIT: 'JOB_MATCH_LIMIT',
} as const;

export type FeatureCode = (typeof FEATURE_CODES)[keyof typeof FEATURE_CODES];

export const BILLING_DEFAULTS = {
  FREE_PLAN_CODE: 'FREE',
  PREMIUM_PLAN_CODE: 'PREMIUM',
  PREMIUM_BILLING_DAYS: 30,
} as const;
